# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:10.16.2
    steps:
      - type: checkout
      - type: shell
        name: "Determine which Projects need to be built"
        command: |
          # Identify modified directories
          LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH?filter=completed&limit=1"
          LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'`

          #first commit in a branch
          if [[ ${LAST_SUCCESSFUL_COMMIT} == "null" ]]; then
            COMMITS="origin/master"
          else
            COMMITS="${CIRCLE_SHA1}..${LAST_SUCCESSFUL_COMMIT}"
          fi

          git diff --name-only $COMMITS | cut -d/ -f1 | sort -u > projects
          echo -e "Modified directories:\n`cat projects`\n"
          cat projects
          while read project; do
              if grep -Fxq $project projects.txt; then
                printf "\nTriggerring build for dir: "$dir
                curl -s -u ${CIRCLE_TOKEN}: \
                  -d build_parameters[CIRCLE_JOB]=${project} \                https://circleci.com/api/v1.1/project/github/$O/$R/tree/$CIRCLE_BRANCH

  build_app_1:
    docker:
      - image: circleci/node:10.16.2
    steps:
      - checkout
      - run:
          name: test app1
          command: |
            cd app1 
            yarn 
            yarn test
  build_app_2:
    docker:
      - image: circleci/node:10.16.2
    steps:
      - checkout
      - run:
          name: test app2
          command: |
            cd app2
            yarn
            yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_app_1
      - build_app_2:
