# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:10.16.2
    steps:
      - checkout
      - run:
          name: Determine which directories have changed
          command: |
            source .circleci/detect_change.sh
            source .circleci/trigger_job.sh
            # git diff --no-commit-id --name-only master | cut -d/ -f1 | sort -u >  projects

  app1:
    docker:
      - image: circleci/node:10.16.2
    steps:
      - checkout
      - run:
          name: build and test app1
          command: |
            cd app1 
            yarn 
            yarn test
  app2:
    docker:
      - image: circleci/node:10.16.2
    steps:
      - checkout
      - run:
          name: build and test app2
          command: |
            cd app2
            yarn
            yarn test

# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - app1
#       - app2:
