# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:
  publish:
    docker:
      - image: circleci/circleci-cli

    steps:
      - checkout
      - compare-url/reconstruct
      - compare-url/use:
          custom-logic: |
            for ORB in folder-containing-orb-subdirs/*/; do

              orbname=$(basename $ORB)

              if [[ $(git diff $COMMIT_RANGE --name-status | grep "$orbname") ]]; then

                echo "publishing ${orbname}"
                echo "test ${CIRCLE_JOB}"
                circleci orb publish ${ORB}/orb.yml namespace/${orbname}@version

              else
                echo "${CIRCLE_COMPARE_URL}/${COMMIT_RANGE}"
                echo "${orbname} not modified; no need to publish"
              fi
            done
          step-name: Publish modified orbs

  build_app_1:
    docker:
      - image: circleci/node:10.16.2
    steps:
      - checkout
      - run:
          name: test app1
          command: |
            cd app1 
            yarn 
            yarn test
  build_app_2:
    docker:
      - image: circleci/node:10.16.2
    steps:
      - checkout
      - run:
          name: test app2
          command: |
            cd app2
            yarn
            yarn test
orbs:
  compare-url: iynere/compare-url@1.2.0
workflows:
  version: 2.1
  publish-orbs:
    jobs:
      - publish

  build_and_test:
    jobs:
      - build_app_1:
        filters:
          branches:
            only: master
      - build_app_2:
          filters:
            branches:
              only: master
      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-# Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-
      # - run: yarn install
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}
      # # run tests!
      # - run: yarn test
